[package]
name = "p3-symmetric"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
proptest = "1.4.0"
proptest-derive = "0.4.0"
itertools = "0.12.0"
